<a href="https://colab.research.google.com/github/D-Yadav/NLP/blob/main/Word_Embedding_Technique_using_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
pip install --upgrade pip

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 8.9 MB/s eta 0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2


In [3]:
import tensorflow as tf
print(tf.__version__)

2.12.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [8]:
### Vocabulary size
voc_size=10000

### One-Hot Encoding

In [9]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
# here iterating through each and every words in sentences
# using one_hot and passing words and voc_size as parameter
# storing into onehot_repr# for every word of each sentences where ever the word is present denoted by 1, that index we're extracting
print(onehot_repr)

[[5904, 378, 4212, 4146], [5904, 378, 4212, 4712], [5904, 4018, 4212, 1455], [3631, 9814, 3574, 7285, 4624], [3631, 9814, 3574, 7285, 4187], [6807, 5904, 8600, 4212, 2611], [8736, 1206, 740, 7285]]


 ### Word Embedding Represntation

In [10]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [15]:
## pre padding
sent_length=8 #considering the maximum length of sentence to be 8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
#pad_sequences will make sure that all the vectors of these words make it 8
#padding='pre' meaning we're adding zeros in the beginning to make the size 8
#padding ='post' meaning we're adding zeros at the last to make size as 8
print(embedded_docs)

[[   0    0    0    0 5904  378 4212 4146]
 [   0    0    0    0 5904  378 4212 4712]
 [   0    0    0    0 5904 4018 4212 1455]
 [   0    0    0 3631 9814 3574 7285 4624]
 [   0    0    0 3631 9814 3574 7285 4187]
 [   0    0    0 6807 5904 8600 4212 2611]
 [   0    0    0    0 8736 1206  740 7285]]


In [16]:
dim=10 #feature representation(dimension) size = 10

In [17]:
model=Sequential() #Created sequential model
model.add(Embedding(voc_size,10,input_length=sent_length))
# Embedding layer is going to work similar to word2vec this is going to train all the neural networks
# voc_size means 10,000 what we denoted above
# 10 is , how many features(dimensions) you want for each vectors , we initialized as dim=10
# input_length = sent_length, means 8 that is being supplied over here
model.compile('adam','mse')
# Compiling with adam optimizer and mse is our loss function

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.predict(embedded_docs[0]) #this is printing the first sentence in 10 dim vector form

1/1 [==============================] - 0s 27ms/step


array([[ 0.02156974,  0.02944449,  0.02797213,  0.00108568, -0.00892942,
         0.02793166,  0.03904739, -0.03377576,  0.00339228,  0.01265473],
       [ 0.02156974,  0.02944449,  0.02797213,  0.00108568, -0.00892942,
         0.02793166,  0.03904739, -0.03377576,  0.00339228,  0.01265473],
       [ 0.02156974,  0.02944449,  0.02797213,  0.00108568, -0.00892942,
         0.02793166,  0.03904739, -0.03377576,  0.00339228,  0.01265473],
       [ 0.02156974,  0.02944449,  0.02797213,  0.00108568, -0.00892942,
         0.02793166,  0.03904739, -0.03377576,  0.00339228,  0.01265473],
       [ 0.02257339, -0.02388223,  0.00384401,  0.01383957,  0.019021  ,
        -0.01812022, -0.01822075, -0.01401328, -0.02330158,  0.02993924],
       [-0.00973014,  0.01032559, -0.04535307,  0.00532162, -0.04651314,
         0.03166132,  0.00795404, -0.0170112 , -0.00345042, -0.00173151],
       [ 0.00433198, -0.03016307,  0.00916332, -0.03107891,  0.00426575,
         0.04911098,  0.03937649, -0.01338568

In [22]:
embedded_docs[0]

array([   0,    0,    0,    0, 5904,  378, 4212, 4146], dtype=int32)

In [25]:
print(model.predict(embedded_docs)) # This is printing all the sentences

1/1 [==============================] - 0s 20ms/step
[[[ 0.02156974  0.02944449  0.02797213  0.00108568 -0.00892942
    0.02793166  0.03904739 -0.03377576  0.00339228  0.01265473]
  [ 0.02156974  0.02944449  0.02797213  0.00108568 -0.00892942
    0.02793166  0.03904739 -0.03377576  0.00339228  0.01265473]
  [ 0.02156974  0.02944449  0.02797213  0.00108568 -0.00892942
    0.02793166  0.03904739 -0.03377576  0.00339228  0.01265473]
  [ 0.02156974  0.02944449  0.02797213  0.00108568 -0.00892942
    0.02793166  0.03904739 -0.03377576  0.00339228  0.01265473]
  [ 0.02257339 -0.02388223  0.00384401  0.01383957  0.019021
   -0.01812022 -0.01822075 -0.01401328 -0.02330158  0.02993924]
  [-0.00973014  0.01032559 -0.04535307  0.00532162 -0.04651314
    0.03166132  0.00795404 -0.0170112  -0.00345042 -0.00173151]
  [ 0.00433198 -0.03016307  0.00916332 -0.03107891  0.00426575
    0.04911098  0.03937649 -0.01338568 -0.04737068  0.00066721]
  [ 0.04654387 -0.04993027 -0.02500857  0.04720838 -0.0323835